xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\arg\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\au\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\befr\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\benl\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\bra\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\ca\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\cl\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\co\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\de\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\ennl\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\es\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\esa\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\fr\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\idn\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\ie\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\it\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\mx\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\mys\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\nl\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\per\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\phl\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\prt\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\sgp\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.css" "\\servermac\Documents\moana\_img\uk\" /E /H /R /Y


xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\arg\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\au\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\befr\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\benl\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\bra\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\ca\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\cl\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\co\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\de\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\ennl\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\es\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\esa\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\fr\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\idn\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\ie\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\it\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\mx\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\mys\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\nl\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\per\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\phl\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\prt\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\sgp\" /E /H /R /Y
xcopy "\\servermac\Documents\moana\_img\us\style.min.css" "\\servermac\Documents\moana\_img\uk\" /E /H /R /Y